# -*- coding: utf-8 -*-
"""h1b_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAj100pEJvGPkAenEOR6OiZVo-pWQ58A
"""
import sys
output="%s %s" % (sys.argv[1], sys.argv[2])
print(output)